language: python
install:

env:
  global:
    - CC_TEST_REPORTER_ID=d1be0f353f6486c96243b0bad4ff26b200b020a3677f100cf531729f852cd7d4
before_script:
    - pip install -r requirements.txt
    - pip install coverage
    - pip install codeclimate-test-reporter
script:
  - pytest
  - codeclimate-test-reporter --file .coverage
after_success:
  - codeclimate-test-reporter