version: "3.7"

services:
  composer:
    image: hyperledger/composer-playground
    container_name: composer
    restart: always
    volumes:
      - ~/.composer:/home/composer/.composer
    ports:
      - "8080:8080"

  rest_api:
      image: hyperledger/composer-rest-server
      container_name: rest_api
      restart: always
      environment:
        - COMPOSER_CARD=CP@digid
        - COMPOSER_NAMESPACES=never
      volumes:
        - ~/.composer:/home/composer/.composer
      ports:
        - "3000:3000"

  cp:
    build:
      context: .
      dockerfile: cp/Dockerfile
    container_name: cp
    restart: always
    environment:
      - APP_NAME=CertificationProvider
    expose:
      - ${cp_port}
    ports:
      - "${cp_port}:5000"

  ap:
    build:
      context: .
      dockerfile: ap/Dockerfile
    container_name: ap
    restart: always
    environment:
      - APP_NAME=AuthenticationProvider
    expose:
      - ${ap_port}
    ports:
      - "${ap_port}:5000"

  service:
    build:
      context: .
      dockerfile: service/Dockerfile
    container_name: service
    restart: always
    environment:
      - APP_NAME=Service
    expose:
      - ${service_port}
    ports:
      - "${service_port}:5000"

  user:
    build:
      context: .
      dockerfile: user/Dockerfile
    container_name: user
    restart: always
    environment:
      - APP_NAME=User
    ports:
      - "5000:5000"

#  nginx:
#    build: ./nginx
#    container_name: nginx
#    restart: always
#    volumes:
#      - ./cp/cp_cert.crt:/etc/nginx/cp_cert.crt
#      - ./cp/cp_cert.key:/etc/nginx/cp_cert.key
#      - ./cp/cp_cert.crt:/etc/nginx/ap_cert.crt
#      - ./cp/cp_cert.key:/etc/nginx/ap_cert.key
#      - ./cp/cp_cert.crt:/etc/nginx/service_cert.crt
#      - ./cp/cp_cert.key:/etc/nginx/service_cert.key
#    ports:
#      - "80:80"
#      - "8080:8080"
#      - "${ap_port}:${ap_port}"
#      - "${cp_port}:${cp_port}"
#      - "${service_port}:${service_port}"

networks:
  default:
    external:
      name: composer_default
