version: "3.7"

services:

  cp:
    build:
      context: cp/
      dockerfile: Dockerfile
    container_name: cp
    restart: always
    environment:
      - APP_NAME=CertificationProvider
    expose:
      - ${cp_port}

  ap:
    build:
      context: ap/
      dockerfile: Dockerfile
    container_name: ap
    restart: always
    environment:
      - APP_NAME=AuthenticationProvider
    expose:
      - ${ap_port}

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - ./cp/cp_cert.crt:/etc/nginx/cp_cert.crt
      - ./cp/cp_cert.key:/etc/nginx/cp_cert.key
      - ./cp/cp_cert.crt:/etc/nginx/ap_cert.crt
      - ./cp/cp_cert.key:/etc/nginx/ap_cert.key
    ports:
      - "80:80"
      - "${ap_port}:${ap_port}"
      - "${cp_port}:${cp_port}"

